### PR TITLE
Extract examples using AutoDoc

### PR DESCRIPTION
**Pull request by fingolfin**
This is perhaps an alternative to PR #8, and thus an alternative way to resolve issue #6.

The removal of utils.gi and utils.gd is of course not strictly necessary, but I felt it made as the code in it really made redundant by the rest of this PR.

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Thanks for this @fingolfin, I'm happy with all of this except the removal of the ability to run the tests etc from inside GAP, I find the functions in `utils.gi` rather useful, although I agree that they are duplicates of other things in this PR. Could you please drop the removal of `utils.g{d, i}` from the PR? Thanks!

**Review by james-d-mitchell — CHANGES_REQUESTED** [review]
Please drop the removal of `utils.g{d,i}`, then I'll be happy to merge.

**Comment by fingolfin** [comment]
@james-d-mitchell rebased, and dropped that commit.

**Comment by james-d-mitchell** [comment]
Awesome thanks

**Pull request merged**
