### PR TITLE
Tweak Travis

### PR DESCRIPTION
**Pull request by wilfwilson**
* Add job to test against GAP stable-4.11
* Test all branches except release candidates, rather than just master.

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
@wilfwilson testing stable-4.11 is certainly needed. Do you think @fingolfin that a default list of GAP branches to test could be specified in https://github.com/gap-system/pkg-ci-scripts.git to avoid revisiting each package to add each new GAP release branch?

I am not sure that we need to allow testing all branches - do you have a specific reason in mind?

**Comment by wilfwilson** [comment]
I wrote an explanation for why I like to allow testing on all branches here:

https://github.com/gap-packages/Digraphs/pull/310#issue-410245838

**Comment by olexandr-konovalov** [comment]
I understood. I've been in a similar situation with wedderga recently, when we were collaborating on a branch in the main repo. Our approach was to have a commit which added that named branch to a list of branches to be tested by Travis, and then remember (what I did) to drop that commit before the final merge.

From time to time collaborators, when working on pull request, were pushing their feature branches to the main repository under gap-packages, instead of their fork (because they have write access). So it was useful that CI was disabled, unless it is explicitly enabled. Otherwise, their pushes would increase load on Travis.

I am still not sure whether we need to allow testing on all branches. One could easily create a PR, call it work in progress, and trigger CI tests that way. OTOH, since gap-packages Travis CI setup is shared, allowing tests on all branches could lead to longer queues.

**Comment by james-d-mitchell** [comment]
I have to say that I more or less agree with @alex-konovalov on this issue. I think I disabled CI on almost all branches, because I became frustrated at the amount of time it was taking for travis to start running a release candidate branch because of various jobs running from other branches, which arguably didn't need to be running (but I don't really remember the specifics).

**Comment by fingolfin** [comment]
@alex-konovalov no such a default list is not possible, as the travis.yml file is processed first, before anything we can do to even retrieve such a list from a central place.

**Comment by wilfwilson** [comment]
@james-d-mitchell I think you're conflating two problems. the only branches that are ever pushed to the `gap-packages/` repositories of your packages 

https://travis-ci.org/github/gap-packages/Digraphs/builds

**Comment by wilfwilson** [comment]
(Closing and reopening was an accident.)

@james-d-mitchell I think you're conflating two things. The real problem is that _all_ gap-packages repos must share the same 5 Travis job slots. That's why you have to wait for so long.

Since the only branches that should be, are essentially ever are, pushed to the `gap-packages` repos of _your_ packages are the master and stable branches (and release candidate branches - discussed later), restricting to only build the master and stable branches on Travis does essentially nothing to reduce the number of Travis builds. Therefore it does nothing to reduce your wait time.

(Side note: scroll back as far as you like on the build history for [Digraphs](https://travis-ci.org/github/gap-packages/Digraphs/builds) or [Semigroups](https://travis-ci.org/github/gap-packages/Semigroups/builds) or [smallsemi](https://travis-ci.org/github/gap-packages/Semigroups/builds) to see that the only branches that are built, with very small, and usually accidental, exceptions, are the master and stable branches.)

I feel like the real issue was that, previously, when you pushed a release candidate branch, and created that PR, Travis would run a build both as a PR (because it runs a build for every PR) and it would run a build for the branch (because you were building all branches). Therefore it would double the length of time taken for your PR to pass all tests. That's why I changed `.travis.yml` in this PR (and in the [Semigroups](https://github.com/gap-packages/Semigroups/pull/665) and [Digraphs](https://github.com/gap-packages/Digraphs/pull/310) packages) to specifically exclude release candidate branches from being tested.

So in my opinion, there is no benefit to the current behaviour, while having appreciable downsides.

**Comment by wilfwilson** [comment]
> I am still not sure whether we need to allow testing on all branches. One could easily create a PR, call it work in progress, and trigger CI tests that way.

If anything, making a PR for every work-in-progress branch would make the situation worse. Currently, any branch that I push to (say) `wilfwilson/smallsemi` gets tested on Travis, as part of my `wilfwilson` Travis account. That means I only have to join the queue for my own builds. But if instead I create a PR on `gap-packages/smallsemi`, that means that any build I push there has to wait for all prior `gap-packages` builds to finish, and moreover it adds yet another build to the `gap-packages` build queue.

**Comment by fingolfin** [comment]
I agree with @wilfwilson's assessment. That limitation on Travis is really annoying. One way to deal with that would of course be to move your packages to a different org, but that'd be kind of a pity.

A better solution would probably be for us to look into making use of GitHub Actions to complement or replace Travis for package tests: AFAIK the limits there are per repo, not per organization (but I might be mistaken), and it seems to work more stable as well.

**Comment by fingolfin** [comment]
See here for a basic showcase for GitHub Actions with a GAP package: https://github.com/gap-packages/polenta/pull/6

**Comment by wilfwilson** [comment]
See #20.

**Pull request closed without merging**
