### PR TITLE
Declare IsSemigroupWithClosedIdempotents only when needed, and for all semigroups

### PR DESCRIPTION
**Pull request by wilfwilson**
Alternative to #3 to address problem raised in https://github.com/gap-packages/Semigroups/pull/605.

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
Thanks @wilfwilson! Perhaps we need to add setup for Travis and Codecov first, and then rebase this PR to test it properly.

**Comment by fingolfin** [comment]
I submitted PR #5 which adds Travis support. Once that is merged, this PR could be rebased.

**Comment by fingolfin** [comment]
@wilfwilson could you rebase this, please?

**Comment by wilfwilson** [comment]
Rebased.

**Comment by james-d-mitchell** [comment]
Thanks all

**Pull request merged**
